services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inquiry_management_development
    ports:
      - "3306:3306"
    volumes:
      - inquiry-db-data:/var/lib/mysql

volumes:
  inquiry-db-data:
